[build]
  command = "zip -r feelfamous-basecamp.zip . -x '*.toml' '*.zip' 'partners.html' 'crib.html' 'dean.html' 'alternaleaf.html' 'basil-bush.html' 'blimburn.html' 'cannatv.html' 'colly.html' 'curaleaf.html' 'dutch-passion.html' 'pax.html' 'royal-queen-seeds.html' 'seedsman.html' 'smoking-paper.html' 'spannabis-magazine.html' 'storz-bickel.html' 'tangy-gifts.html' 'vapman.html'"
  publish = "."
